application:
  url: http://localhost:8080
  hourValidateTokenForRegistration: 10
  emailName: Check email

  sms:
    mock: true
    login: martinstein150990
    password: alescha333

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydatabase
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 465
    username: martinstein150990@gmail.com
    password: alescha333
    protocol: smtps